spring:
  datasource:
    username: root
    password: tongminh1510
    # If no schema is provided, it will be auto-created
    url: jdbc:mysql://localhost:3306/course
  session:
    store-type=jdbc:
      session:
        timeout=180:
  jdbc:
    initialize-schema=always:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    # Generate tables based on entities (update them if they exist, do not drop them)
    generate-ddl: true
    # Show SQL statements in the console
    show-sql: true
    hibernate:
      ddl-auto: none
  docker:
    compose:
      enabled=false: